### ISSUE TITLE
数据库导入错误

### ISSUE THREAD

**Issue by guyingd** [UtopiaXC/MDUI-Blog#2]
CREATE TABLE `indexes`  (  `IID` int(10) NOT NULL AUTO_INCREMENT,  `index_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,  PRIMARY KEY (`IID`) USING BTREE) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic

**Comment by guyingd** [comment]
MySQL 返回： 

#1273 - Unknown collation: 'utf8mb4_0900_ai_ci

**Comment by UtopiaXC** [comment]
MySQL版本需要8.0以上，或者把.sql文件里的utf8mb4_0900_ai_ci替换为utf8_general_ci
