### ISSUE TITLE
替换utf8mb4_0900_ai_ci还是不行

### ISSUE THREAD

**Issue by guyingd** [UtopiaXC/MDUI-Blog#3]
CREATE TABLE `indexes`  (
  `IID` int(10) NOT NULL AUTO_INCREMENT,
  `index_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`IID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic

MySQL 返回
#1253 - COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'

**Comment by guyingd** [comment]
也可能是我主机问题，用的是ksweb手机搭建的主机，用来测试源码的。

**Comment by UtopiaXC** [comment]
这个问题出在MySQL上，MySQL8.0以前的版本没有引入相应字符集utf8mb4_0900_ai_ci，所以执行不了脚本。实在不行其实可以把字符集相关的字段删掉，应该会自动设置为当前MySQL版本对应的字符集。
